/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
import com.google.protobuf.gradle.*

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    application
    id("com.google.protobuf") version "0.9.5"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation("com.graphql-java:graphql-java:23.0")

    implementation("io.grpc:grpc-protobuf:1.82.1")
    implementation("io.grpc:grpc-stub:1.82.1")
    runtimeOnly("io.grpc:grpc-netty-shaded:1.82.1")

    // Needed for @Generated annotation on JDK 9+ (grpc codegen references it)
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

    // REST (Javalin + embedded Jetty)
    implementation("io.javalin:javalin:6.3.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    // SLF4J binding — required by Javalin/Jetty for log output
    implementation("org.slf4j:slf4j-simple:2.0.13")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.5"
    }
    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.82.1"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                create("grpc")
            }
        }
    }
}


testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

application {
    // Switch to the current hands-on main class, or run any directly from the IDE:
    //   Locking      : org.pk.practices.design.locking.LockingDemo          (no port — CLI)
    //   Bloom Filter : org.pk.practices.design.bloomfilter.BloomFilterDemo   (no port — CLI)
    //   EDI          : org.pk.practices.design.api.edi.EdiDemo               (no port — CLI)
    //   WebSocket    : org.pk.practices.design.api.websocket.ChatServer       (port 8083)
    //   GraphQL      : org.pk.practices.design.api.graphql.GraphQlServer      (port 8082)
    //   REST         : org.pk.practices.design.api.rest.RestApiServer          (port 8081)
    //   gRPC         : org.pk.practices.design.api.grpc.client.Tester          (port 8080)
    mainClass = "org.pk.practices.design.locking.LockingDemo"
}

// -parameters embeds constructor parameter names in bytecode.
// Jackson uses them to deserialize JSON into Java records without @JsonProperty annotations.
tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}
