package org.pk.practices.design.api.websocket.model;

import java.time.Instant;

/**
 * The wire format for every message exchanged over the WebSocket connection.
 *
 * <p>All messages — whether initiated by a client (CHAT) or generated by the server
 * (JOIN, LEAVE, ERROR) — share this envelope. Using a single type simplifies client
 * parsing: deserialize once, switch on {@link #type()}.
 *
 * <p>Jackson serializes this record to JSON for transmission:
 * <pre>
 * {
 *   "type":      "CHAT",
 *   "sender":    "Alice",
 *   "room":      "general",
 *   "content":   "Hello!",
 *   "timestamp": "2026-07-19T10:00:00.000Z"
 * }
 * </pre>
 *
 * <p>Factory methods keep construction sites readable and centralise the timestamp
 * so no call site forgets to set it.
 *
 * @param type      the kind of event this message represents
 * @param sender    username of the originating user, or {@code "server"} for system messages
 * @param room      the room this message belongs to
 * @param content   the human-readable body of the message
 * @param timestamp ISO-8601 UTC instant at which the message was created
 */
public record ChatMessage(MessageType type, String sender, String room, String content, String timestamp) {

    /** Creates a JOIN notification broadcast to the room when a new user connects. */
    public static ChatMessage join(String sender, String room) {
        return new ChatMessage(MessageType.JOIN, sender, room,
                sender + " joined the room", now());
    }

    /** Creates a CHAT message from a user to the room. */
    public static ChatMessage chat(String sender, String room, String content) {
        return new ChatMessage(MessageType.CHAT, sender, room, content, now());
    }

    /** Creates a LEAVE notification broadcast to the room when a user disconnects. */
    public static ChatMessage leave(String sender, String room) {
        return new ChatMessage(MessageType.LEAVE, sender, room,
                sender + " left the room", now());
    }

    /** Creates a server-originated error message sent to a specific client. */
    public static ChatMessage error(String room, String detail) {
        return new ChatMessage(MessageType.ERROR, "server", room, detail, now());
    }

    private static String now() {
        return Instant.now().toString();
    }
}
